### ISSUE TITLE
Specify output field name for simple aggregation

### ISSUE THREAD

**Issue by alimanfoo** [petl-developers/petl#370]
Add an argument to aggregate() to allow output field name specification by user in the case of simple aggregation.

**Comment by rsyring** [comment]
I do think it would be more intuitive to have this option than to use the recommendation in the mailing this.  Thanks for adding the issue.

**Comment by bmaggard** [comment]
@juarezr Is this OK to close?

**Comment by juarezr** [comment]
> @juarezr Is this OK to close?

@bmaggard ,

Thanks for spotting it!
