### ISSUE TITLE
Question: removal of "if exists"

### ISSUE THREAD

**Issue by Jimexist** [petl-developers/petl#376]
I saw that `if exists` was removed in https://github.com/alimanfoo/petl/commit/62f35c542119bc32e782681a15381972072e043e#diff-57ad97c12e2a16f74c54d7bb4d8e332cL252 - any reason why? Now that when I try to use `create=True` and `drop=True` with `todb` and the target table does not exist, it will raise exception.

**Comment by Jimexist** [comment]
NVM i saw this https://github.com/alimanfoo/petl/issues/317 - but this is maybe some kind of annoying know that I have to use different params depending on whether the table previously existed, with an intention to drop whatsoever.

**Comment by alimanfoo** [comment]
Hi Jiayu, thanks for the message. As you saw in #317 it is not
straightforward to support "IF EXISTS" in a way that is portable across all
major databases. I realise it is annoying that you have to use different
params depending on whether or not the table exists. If you have a proposal
I'd be happy to consider it.

On Tuesday, May 17, 2016, Jiayu Liu <notifications@github.com> wrote:

> NVM i saw this #317 <https://github.com/alimanfoo/petl/issues/317> - but
> this is maybe some kind of annoying know that I have to use different
> params depending on whether the table previously existed, with an intention
> to drop whatsoever.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/376#issuecomment-219633804>
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721
