### ISSUE TITLE
Python Petl - _csv.Error: line contains NULL byte

### ISSUE THREAD

**Issue by garaujodealmeida** [petl-developers/petl#380]
I'm running this:

```
table = petl.fromcsv('file.txt', delimiter = ',' , encoding = 'utf-8) 
petl.todb(table, connection, 'table') 
```

And i am getting this error on insert step:

```

File "/usr/local/lib/python2.7/dist-packages/petl/util/base.py", line 28, in __len__ 
 return sum(1 for _ in self) 
 File "/usr/local/lib/python2.7/dist-packages/petl/util/base.py", line 28, in <genexpr> 
 return sum(1 for _ in self) 
 File "/usr/local/lib/python2.7/dist-packages/petl/io/csv_py2.py", line 45, in __iter__ 
 for row in reader: 
 File "/usr/local/lib/python2.7/dist-packages/petl/io/csv_py2.py", line 149, in next 
 row = self.reader.next() 
_csv.Error: line contains NULL byte
```

What i can to do to solve this problem?

**Comment by alimanfoo** [comment]
Hi Gabriel, this is not something I have come across myself so I don't have
an answer I'm afraid. I guess the CSV file you are reading contains a NULL
byte somewhere, my next step would be to try and find these and remove them.

On Monday, June 27, 2016, Gabriel Almeida <notifications@github.com> wrote:

> I'm running this:
>
> table = petl.fromcsv('file.txt', delimiter = ',' , encoding = 'utf-8)
> petl.todb(table, connection, 'table')
>
> And i am getting this error on insert step:
>
>
> File "/usr/local/lib/python2.7/dist-packages/petl/util/base.py", line 28, in __len__
>  return sum(1 for _ in self)
>  File "/usr/local/lib/python2.7/dist-packages/petl/util/base.py", line 28, in <genexpr>
>  return sum(1 for _ in self)
>  File "/usr/local/lib/python2.7/dist-packages/petl/io/csv_py2.py", line 45, in __iter__
>  for row in reader:
>  File "/usr/local/lib/python2.7/dist-packages/petl/io/csv_py2.py", line 149, in next
>  row = self.reader.next()
> _csv.Error: line contains NULL byte
>
> What i can to do to solve this problem?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/petl/issues/380>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8Qk7mJ2c2nPiGdeXRguFDJlZU0xpwks5qP9NMgaJpZM4I_Gtq>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721
