### ISSUE TITLE
sortheader() with duplicate column names overlays values

### ISSUE THREAD

**Issue by bmaggard** [petl-developers/petl#392]
``` python
import petl as etl
```

``` python
t1 = etl.wrap([
    ['id', 'foo', 'bar', 'baz'],
    ['a', 1, 2, 3],
    ['b', 4, 5, 6]])
```

``` python
t1.sortheader()
```

<table class='petl'>
<thead>
<tr>
<th>bar</th>
<th>baz</th>
<th>foo</th>
<th>id</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: right'>2</td>
<td style='text-align: right'>3</td>
<td style='text-align: right'>1</td>
<td>a</td>
</tr>
<tr>
<td style='text-align: right'>5</td>
<td style='text-align: right'>6</td>
<td style='text-align: right'>4</td>
<td>b</td>
</tr>
</tbody>
</table>

``` python
t2 = etl.wrap([
    ['id', 'foo', 'foo', 'foo'],
    ['a', 1, 2, 3],
    ['b', 4, 5, 6]])
```

``` python
t2.sortheader()
```

<table class='petl'>
<thead>
<tr>
<th>foo</th>
<th>foo</th>
<th>foo</th>
<th>id</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: right'>1</td>
<td style='text-align: right'>1</td>
<td style='text-align: right'>1</td>
<td>a</td>
</tr>
<tr>
<td style='text-align: right'>4</td>
<td style='text-align: right'>4</td>
<td style='text-align: right'>4</td>
<td>b</td>
</tr>
</tbody>
</table>

**Comment by alimanfoo** [comment]
Thanks @bmaggard, it would be good if possible to fix this so that sorting of columns with the same name is stable and doesn't overwrite data.
