### ISSUE TITLE
fromdb & look not found on petl

### ISSUE THREAD

**Issue by manel00** [petl-developers/petl#439]
Hi,

I'd like to know what version of Python must be set up to run petl ok, because I've tested both (2.7, 3.6+) and give me errors, I cannot do anything between databases, please would you mind to give me some clues to do ETL from postgres to postgres? 

Thanks anyway

**Comment by alimanfoo** [comment]
Hi Manel,

There are some examples using psycopg2 in the docstring for fromdb()...

http://petl.readthedocs.io/en/latest/io.html#petl.io.db.fromdb

I haven't tried it in a while but has been tested on py27 and py35.

Not much more I can do to help without a minimal reproducible code example
and a stack trace of the error you're getting.

Cheers,
Alistair

**Comment by manel00** [comment]
Recently added new issue, that was the problem, thank you for your interesting
