### ISSUE TITLE
column equivalent of `rowslice`?

### ISSUE THREAD

**Issue by gamesbook** [petl-developers/petl#459]
I see a number of methods for dealing with columns based on their named headers; but I need to handle an even simpler case.  

If I load a table from an .xls file (NOT .xlsx) that has no header row, and need to remove ("slice off") a set of columns based on their index position - say, columns 3 to 5 - what method should I use for that?

#### Version and installation information

* Value of ``petl.__version__``:  '1.2.0'
* Version of Python interpreter: 3.6.6
* Operating system (Linux/Windows/Mac): Linux Mint (16.04)
* How petl was installed (e.g., "using pip into virtual environment", or "using conda"): pip

**Comment by alimanfoo** [comment]
Hi @gamesbook, you should be able to use cut, e.g.:

```python
tbl = etl.fromxls('foo.xls').cut(*range(3, 6))
```

**Comment by EOSIT** [comment]
@alimanfoo Thanks so much!

**Comment by alimanfoo** [comment]
No problem!
