### ISSUE TITLE
How to use petl to handle clob or blob datatype in oracle? 

### ISSUE THREAD

**Issue by joyear2019** [petl-developers/petl#479]
Hi everyone, can petl extract clob or blob data from oracle?

**Comment by joyear2019** [comment]
Looking forward to your reply, Thx! @alimanfoo

**Comment by alimanfoo** [comment]
Hi @joyear2019, petl is a thin wrapper around the database client library, so if the client library can extract clob or blob data then it will get passed through to petl. My best suggestion would be to try making a query first using the database client library directly. If that works, you could then try doing the same thing via petl. Hope that helps.

**Comment by joyear2019** [comment]
Thanks for your advice, I'll try out your suggestion.
