### ISSUE TITLE
Spark support

### ISSUE THREAD

**Issue by vietvudanh** [petl-developers/petl#481]
I have just started look into petl and I wonder if the package support using Spark?
Because for big data, using pandas/numpy is impossible.

I have skim through the documentation and also the code, it seems there is nothing indicate that. So is there any plan in the future?

**Comment by alimanfoo** [comment]
Hi @vietvudanh, petl is not really optimised for large datasets. I would suggest looking at dask dataframe, which can make use of various parallel execution engines: https://docs.dask.org/en/latest/dataframe.html

**Comment by vietvudanh** [comment]
> Hi @vietvudanh, petl is not really optimised for large datasets. I would suggest looking at dask dataframe, which can make use of various parallel execution engines: https://docs.dask.org/en/latest/dataframe.html

Thank you for the reply. I have already tried dask, not on the whole cluster though because of lacking resources.

At this point sticking to `spark` is still the best option for me. Was just wondering if it can intergrated into spark since I am using python anyway for visualization on top of pyspark.

**Comment by alimanfoo** [comment]
This may be of interest: https://docs.dask.org/en/stable/spark.html#reasons-to-choose-both
