### ISSUE TITLE
Issue with derived class of petl.io.base.Table - >max. recursion depth exceeded

### ISSUE THREAD

**Issue by drozdse1** [petl-developers/petl#483]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
from petl.io.base import Table

class DataObject(Table):
    pass

dataobject = DataObject()

print(dataobject)
# RecursionError: maximum recursion depth exceeded while calling a Python object

```

#### Problem description

I want to build a custom version of _petl.io.base.Table_. But I ran into an **RecursionError** ("RecursionError: maximum recursion depth exceeded while calling a Python object"). The behavior seems to have its cause in the **\_\_getitem\_\_** method. I'm not sure if this is a real **bug**, but I was hoping that someone could explain me how to build a custom version of the petl _Table_ class in a proper way.

#### Version and installation information

* petl version 1.3.0
* Version of Python Interpreter 3.6.3
* Operating system Windows
* How petl was installed using pep -> pep install petl

**Comment by arturponinski** [comment]
@drozdse1 this is due to the fact, that your inherited class does not implement `__iter__` and base implementation of `IterContainer` assumes it is a valid iterator.
Since it might be confusing, @juarezr I propose a default implementation raising NotImplementedError
