### ISSUE TITLE
Oracle - TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by be-rock** [petl-developers/petl#513]
Hi, I am unable to write to json because of `Object of type datetime is not JSON serializable`
```python
import petl as etl
import cx_Oracle
connection = cx_Oracle.connect('myusername', os.getenv('__OPW'), 'myoracleservice')
table = etl.fromdb(connection, 'SELECT * FROM myschema.mytable')
print(table)
+----+-------------------------------------+
| C1 | C2                                  |
+====+=====================================+
|  1 | datetime.datetime(2020, 1, 1, 0, 0) |
+----+-------------------------------------+
etl.tojson(table, '/tmp/example.json')

TypeError: Object of type datetime is not JSON serializable


sqlplus> desc myschema.mytable
Name                         Null?    Type
 ---------------------------- -------- -----------------
 C1                                    NUMBER(38)
 C2                                    DATE

```

#### Problem description

Unable to write to json

#### Version and installation information

* Value of ``petl.__version__`` 
1.6.3
* Version information for any third-party package dependencies that are relevant
cx_oracle 7.2.3
* Version of Python interpreter
3.8.4
* Operating system (Linux/Windows/Mac)
Mac
* How petl was installed (e.g., "using pip into virtual environment", or "using conda")
`conda install petl`

Thanks.

**Comment by juarezr** [comment]
Hi @be-rock ,

I don't know if `petl` was designed to make automatic conversion for python datetime types.

Also handling datetime to string is tricky because one can need many formats according to the usage.

What happen in your case if you use a [transformation](https://petl.readthedocs.io/en/stable/transform.html#petl.transform.conversions.convert) for manually converting your datetimes?

**Comment by be-rock** [comment]
That worked perfectly, thank you @juarezr !

```python
import os

import petl as etl
import cx_Oracle
connection = cx_Oracle.connect('myusername', os.getenv('__OPW'), 'myoracleservice')
table = etl.fromdb(connection, 'SELECT * FROM myschema.mytable')
print(table)
+----+-------------------------------------+
| C1 | C2                                  |
+====+=====================================+
|  1 | datetime.datetime(2020, 1, 1, 0, 0) |
+----+-------------------------------------+
table_mod = etl.convert(table_raw, 'C2', lambda x: str(x))
print(table_mod)
+----+-----------------------+
| C1 | C2                    |
+====+=======================+
|  1 | '2020-01-01 00:00:00' |
+----+-----------------------+
etl.tojson(table_mod, '/tmp/example.json')
!cat /tmp/example.json
[{"C1": 1, "C2": "2020-01-01 00:00:00"}]
```
