### ISSUE TITLE
How to use convert with custom function and reference row

### ISSUE THREAD

**Issue by carlcorder** [petl-developers/petl#542]
Would it be possible to get an example placed in the documentation of using convert with a custom function that has reference to the row? I assume something like this should work?

```python
table = [[a,b,c], [1,2,3]]

def my_func(row):
    return row['b'] + row['c']
    
etl.convert(table, 'a', my_func)

# [[a,b,c], [5,2,3]]
```

**Comment by juarezr** [comment]
Hi @carlcorder ,

Looks good to me.

Would you consider making a PR adding an example in the [convert](https://petl.readthedocs.io/en/stable/transform.html#petl.transform.conversions.convert) function documentation ? 
I would be happy to review and integrate your proposal.

**Comment by javidy** [comment]
Hi @juarezr ,

I'd be happy to help with this issue. Can I take this forward?

**Comment by juarezr** [comment]
Sure.
Please, tell me if you would have any questions.

**Comment by carlcorder** [comment]
Thanks @javidy! I forgot that I also need to pass the `pass_row=True` keyword in order for the above to work.

**Comment by javidy** [comment]
Thanks @carlcorder for comment. I'll take that into account.

**Comment by javidy** [comment]
For some reason I couldn't get it worked. When I try below code, I get `None` instead of sum of fields.
Could you please check if I miss anything?

```python
import petl as etl

def my_func(row):
    return row.bar + row.baz
    #row['bar'] + row['baz']

table1 = [['foo', 'bar', 'baz'], ['A', 2.4, 12]]

table2 = etl.convert(table1, 'foo', my_func, pass_row=True)
```
Here is the screenshot
<img width="614" alt="convert_custom" src="https://user-images.githubusercontent.com/7736273/111884895-c2385880-89c4-11eb-9ce8-67783cb2a8cb.png">

**Comment by carlcorder** [comment]
Hey Javidy, my hunch is that `my_func` is not getting called. I think the issue here is that the signature of the function needs to be `def my_func(val, row):` ?

**Comment by javidy** [comment]
hey @carlcorder  ,

you're right about that. It works when I change the signature of the function. 

<img width="504" alt="Screenshot 2021-03-22 at 19 59 56" src="https://user-images.githubusercontent.com/7736273/112043733-43b8f380-8b49-11eb-93fd-5b47e289d56d.png">
