### ISSUE TITLE
Contributing.rst documentation is failing on make html

### ISSUE THREAD

**Issue by mzyndul** [petl-developers/petl#553]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```shell
Documentation is built with `sphinx <http://sphinx-doc.org/>`_. To build::

    $ pip install sphinx sphinx_issues
    $ cd docs
    $ make html

```

#### Problem description

Creating docs doesn't work out of the box as described in documentation:

```shell
➜ make html                  
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.5.4

Extension error:
Could not import extension sphinx_issues (exception: No module named 'sphinx_issues')
make: *** [Makefile:40: html] Error 2
```

Since the problem is quite obvious, documentation should mention about missing package sphinx_issues, I would see one of the following as the solution:

```shell
pip install sphinx sphinx_issues
```

OR

```shell
pip install -r requirements-docs.txt
```

while I think using requirements file is better.

I could create PR for this.

**Comment by juarezr** [comment]
Oh! Please, go ahead and make your PR.

I think this code path needs some love. :)
Also, there is a way for building docs using `tox`.

I'm glad to help if you need any help.

**Comment by mzyndul** [comment]
PR merged, I close it.

**Comment by juarezr** [comment]
Ok, thanks.
If you have other improvements, please open a new PR.
