### ISSUE TITLE
Broken `petl.version` because requirements-docs has nothing pinned

### ISSUE THREAD

**Issue by tomwojcik** [petl-developers/petl#655]
There's a bug in `setuptools_scm`

https://github.com/pypa/setuptools_scm/issues/905

Petl does not use a pinned version

https://github.com/petl-developers/petl/blob/e829532e2ed350d00b96680d2d6774dec4a7f2e0/requirements-docs.txt#L2

**Comment by tomwojcik** [comment]
This issue should be fixed in a moment, so new petl installs should work again, but I highly recommend pinning the compatible versions.

**Comment by bdh1011** [comment]
I'm having serious trouble with this issue right now.. 😿

**Comment by tomwojcik-adverity** [comment]
@bdh1011 fixed upstream 8 minutes ago https://github.com/pypa/setuptools_scm/releases/tag/v8.0.1

**Comment by juarezr** [comment]
@tomwojcik , @bdh1011 ,

Please tell me if the bug persists for reopening this issue.
