### ISSUE TITLE
Feature Request: support for 3.12

### ISSUE THREAD

**Issue by shaunagm** [petl-developers/petl#664]
### Explain why petl needs this feature?

Hi! Our project [Parsons](https://github.com/move-coop/parsons/) depends on PETL. We'd like to support Python 3.12 but need to wait for PETL to support it first. It looks like you've got 3.12 support merged into main but not released on PyPI yet. Do you have a timeline for when you're going to cut your next release/officially support 3.12?

### Describe the solution you would like

Apologies if this is the wrong place to make this request, I looked at https://groups.google.com/g/python-etl/ but it seems to be full of spam.

### Additional Notes

Thank you so much for your work on PETL!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juarezr** [comment]
@shaunagm 

- Current version v1.7.15 should work fine with python3.12
- There are no changes in the runtime code of this library specific to Python v3.12
- The last changes committed are just:
  - running the test suite with Python v3.12
  - adding descriptions to the release package marking Python 3.12 as "supported"
 - If you find any problem regarding Python 3.12, please let us know or open a new issue with a reproducible test case.
